### PR TITLE
fix(builtins)!: match scopes exactly instead of normalizing them

### LINKED ISSUE #116: [functional] HasScope is case-insensitive, rewrites bare scopes, and truncates multi-colon scopes
## Summary
`HasScope` matching is not exact: it lowercases values, rewrites a bare scope like `project` to `read:project`, and discards components after the second `:`. OAuth scope values are case-sensitive and opaque (RFC 6749 §3.3).

## Location
- `packages/builtins/src/rules/HasScope.mts:27-35` (`scope.split(":")`, `const [perm, resource] = parts`, lowercase)

## Why it matters
`read:PROJECT` currently satisfies `read:project`, and `read:project:restricted` collapses to `read:project` — so a scope intended to be narrower is treated as the broader one. Scope comparison that is case-insensitive and truncating can over-grant.

## Suggested fix
Match the issuer-defined scope string exactly, or perform only an explicit, validated mapping; reject or explicitly handle scopes with more than one `:`.

## Detected by
Verifier-security (Minor) + functional-spec + Codex (Important).

---
_Filed from a multi-agent production-readiness review (2026-08-26): 4 Claude subagents (security/ops/functional) + Codex CLI security/perf audit, cross-checked. `Detected by` notes independent agreement._

### PR DESCRIPTION
**Pull request by y1o1**
## Summary

`HasScope` did not compare scopes — it normalized them first, three different ways, and each normalization could satisfy a requirement the issuer never granted. OAuth 2.0 scope values are case-sensitive opaque strings ([RFC 6749 §3.3](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3)), so the rule now compares what the issuer actually wrote.

**BREAKING** — pre-1.0 (0.x), taken deliberately to stabilize the matching semantics before 1.0.

## The three semantics changes

| | Old | New |
| --- | --- | --- |
| **Case** | `read:PROJECT` satisfied `read:project` (both sides lowercased) | Case-sensitive; `read:PROJECT` is denied |
| **Multi-colon** | `scope.split(":")` destructured to two parts, dropping the rest: `read:project:restricted` satisfied `read:project` — a deliberately narrowed grant collapsed into the broader one. The same truncation meant `read:project:restricted` never satisfied *its own* requirement either. | Never split. It matches only an identical value — so the over-grant is closed **and** the narrow scope now matches its own rule |
| **Bare scope** | A granted `project` was always rewritten to `read:project` | Compared literally; rewrite is opt-in |

## Opt-in flag

**`allowBareScopeRewrite`** — default `false`.

- HOCON: `{ collector = "ResourceActionScopeRuleCollector", allowBareScopeRewrite = true }`
- TypeScript: `new ResourceActionScopeRuleCollector({ allowBareScopeRewrite: true })`, or `new HasScope(scope, { allowBareScopeRewrite: true })`

Even when enabled, only a scope containing **no** `:` is rewritten. `project:restricted` is left alone — which segment is the action is unknowable, and guessing is exactly what caused the truncation over-grant. The collector validates the flag is a boolean at construction time, alongside the existing `scopeless` check.

Also: a non-string entry in `ATTR_SCOPES` now denies instead of throwing `TypeError: scope.toLowerCase is not a function`, which surfaced as a 500 rather than a decision.

## Effect on the shipped standalone config

`templates/standalone/config/application.conf` configures `ResourceActionScopeRuleCollector` with no options, so it picks up the new defaults. **What it grants narrows** for any deployment whose issuer emits bare resource names (`document`) or scopes cased differently from `{action}:{resourceType}` — those tokens now get denied and must set `allowBareScopeRewrite = true` (case differences have no opt-out and must be fixed at the issuer). A deployment whose issuer emits exact `read:document`-style scopes is unaffected. The config now carries a comment pointing at the opt-in.

Note this config is separately known to be broken by #113 (it enables `ResourceActionPermissionRuleCollector` with no permission supplier, so it denies everything as shipped). **This PR does not touch that** and does not fix or worsen it — the smoke tests here, like the existing ones, exercise a scope-only config.

## Tests

TDD per AGENTS.md — tests written first and watched fail. 13 unit tests failed against the old implementation (one per defect, including the `TypeError`), plus 2 of the 3 new smoke tests; the third guards the config-passthrough path.

- `HasScope.test.mts` — restructured into `case sensitivity`, `multi-colon scopes`, `bare-scope rewrite (opt-in)`, `malformed attribute values`
- `ResourceActionScopeRuleCollector.test.mts` — flag passthrough, default-off, boolean validation (incl. rejecting an explicit `null`)
- `smoke.test.mts` — end-to-end through `AppConfigSchema` → `createApp`, proving the opt-in survives config parsing (the only path a deployment has to re-enable the rewrite)

Full suite across every workspace, `pnpm lint`, and `pnpm -r run build` all green (rebased onto develop after #139):

```
create-app           65 passed
packages/core        59 passed
packages/builtins   441 passed  (+22)
packages/server     166 passed
templates/standalone 27 passed  (+3)
tests/integration    35 passed
                    793 passed, 0 failed
```

Closes #116

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: packages/builtins/src/rules/collectors/ResourceActionScopeRuleCollector.mts [hunk 1]
```diff
@@ -60,13 +74,21 @@ export class ResourceActionScopeRuleCollector implements RuleCollector {
...
 		}
 		this.scopeless = scopeless;
+
+		const allowBareScopeRewrite = config?.allowBareScopeRewrite ?? false;
+		if (typeof allowBareScopeRewrite !== "boolean") {
+			throw new Error(
+				`ResourceActionScopeRuleCollector: allowBareScopeRewrite must be a boolean, got "${allowBareScopeRewrite}"`,
+			);
+		}
+		this.allowBareScopeRewrite = allowBareScopeRewrite;
```
[the remark this answers is not in the document]
Comment (y1o1) [reply packages/builtins/src/rules/collectors/ResourceActionScopeRuleCollector.mts]: Good catch — fixed in 0987f65. `null` did slip through: `?? false` treated it as "unset", so a misconfiguration was silently accepted as the default rather than rejected. The raw value is now validated before defaulting, and only an absent key falls back:

```ts
const rawRewrite: unknown = config?.allowBareScopeRewrite;
if (rawRewrite !== undefined && typeof rawRewrite !== "boolean") throw ...
this.allowBareScopeRewrite = rawRewrite ?? false;
```

Added tests for the explicit-`null` rejection and for an omitted key still defaulting cleanly.

File: packages/builtins/src/rules/HasScope.mts [hunk 2]
```diff
@@ -4,33 +4,78 @@
...
+		this.allowBareScopeRewrite = options?.allowBareScopeRewrite ?? false;
 	}
 
 	verify(attrs: Attributes): boolean {
-		const scopes = (attrs.get(ATTR_SCOPES) as string[] | undefined) ?? [];
-		return scopes.some((s) => this.matchScopes(s, this.scope));
+		const scopes = (attrs.get(ATTR_SCOPES) as unknown[] | undefined) ?? [];
+		if (!Array.isArray(scopes)) return false;
+		return scopes.some((s) => typeof s === "string" && this.matchScope(s, this.scope));
 	}
```
[the remark this answers is not in the document]
Comment (y1o1) [reply packages/builtins/src/rules/HasScope.mts]: Agreed — changed in 0987f65 to `const scopes: unknown = attrs.get(ATTR_SCOPES);` followed by the `Array.isArray` narrowing. The old `as unknown[] | undefined` cast asserted the array-ness that the very next line was checking, and the trailing `?? []` was dead once `Array.isArray` handled the undefined case too. Runtime behavior is unchanged.
